import { useEffect, useState } from 'react';
import Head from 'next/head';
import { motion } from 'framer-motion';
import { useRouter } from 'next/router';

import Navabar from '../components/Navbar';
import Menu from '../components/Menu';
import Footer from '../components/Footer';

import en from '../locales/en';
import it from '../locales/it';

const options = {
  initial: {
    opacity: 0,
    y: '-100vh',
  },
  animate: {
    opacity: 1,
    y: '0vh',
  },
  transition: {
    ease: [0.85, 0, 0.15, 1],
    duration: 1.2,
    // delay: 0.6,
  },
};

const MainLayout = ({ children }) => {
  const router = useRouter();
  const { locale } = router;
  const t = locale === 'en' ? en : it;
  const currentPath = router.asPath;

  // States
  const [isOpen, setIsOpen] = useState(false);
  const [selectedLanguage, setSelectedLanguage] = useState(locale);

  useEffect(() => {
    if (isOpen) {
      document.body.classList.add('overflow-hidden');
    }

    return () => {
      document.body.classList.remove('overflow-hidden');
    };
  }, [isOpen]);

  // Language switch

  const handleChangeLang = language => {
    router.push(currentPath, currentPath, { locale: language });
    setSelectedLanguage(language);
  };

  return (
    <div>
      <Head>
        <title>El Valet Canelli aaa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="overflow-x-hidden font-light text-white">
        <Navabar isOpen={isOpen} setIsOpen={setIsOpen} />
        {children}
        <Footer />
      </div>

      <motion.div
        initial={options.initial}
        animate={isOpen ? options.animate : options.initial}
        transition={options.transition}
        className="fixed top-0 left-0 z-20 w-screen h-screen overflow-hidden overflow-x-hidden bg-black menu-container"
      >
        <Menu
          isOpen={isOpen}
          setIsOpen={setIsOpen}
          selectedLanguage={selectedLanguage}
          setSelectedLanguage={setSelectedLanguage}
          handleChangeLang={handleChangeLang}
        />
      </motion.div>
    </div>
  );
};

export default MainLayout;
