import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex items-center justify-center">
        <h1 className="text-4xl text-center">
          Ciao Cami!
          <br />
          Welcome to your project boilerplate.
        </h1>
      </main>
    </div>
  );
}
